#!/usr/bin/env python3
"""The Discord telemetry — the corpus's third surface, and its deepest practice space.

Every Discord channel heading in the archive carries its own message volume:

    ### **Unsloth AI (Daniel Han) ▷ #[general](...)** (1123 messages🔥🔥🔥):

That is 31,688 channel-day records over 2.15M messages and 56 servers, and it is
behavioural rather than editorial: nobody chose to write those messages for a
newsletter. Twitter measures what was announced and Reddit what practitioners
discussed; Discord measures what communities were *doing*, hour by hour.

Two analyses:

1. **Community lifecycle.** Per-server message volume over time, with first and
   last appearance. Servers are born, grow and die inside the window.
2. **Discord as a third text surface.** The same patterns measured in
   `sections.py` for Twitter and Reddit, computed inside the Discord recap, so
   the announcement/practice split becomes a three-way comparison.

Coverage limit, stated up front: Discord sampling runs 2024-05 to 2026-03 and
then stops entirely — the newsletter dropped it. Nothing here can speak to 2026H2,
and the decline of any Discord-native subject after 2026-03 is the instrument,
not the field.

Usage:
    python3 analysis/methods/discord.py
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
import sys

from recaps import sections_of  # one shared, tested recap splitter

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
ARTICLES = REPO / "articles"
OUT = REPO / "analysis" / "discord.md"

FRONT = re.compile(r"\A---\n.*?\n---\n", re.DOTALL)
HEAD = re.compile(r"^#\s+AI (Twitter|Reddit|Discord) Recap.*$", re.M | re.I)
CHANNEL = re.compile(
    r"^###\s+\*\*(?P<server>.+?)\s+▷\s+#\[(?P<chan>[^\]]+)\]\([^)]*\)\*\*\s*\((?P<n>\d+)\s+messages",
    re.M)

# Same patterns as sections.py, so the three surfaces are directly comparable.
PATTERNS = {
    "agentic": r"\bagentic\b|\bagents?\b",
    "fine-tuning": r"fine[- ]?tun|\bLoRA\b",
    "quantization": r"quantiz|\bGGUF\b|\bAWQ\b|\bGPTQ\b|\bfp8\b|\bQ[45]_K",
    "RAG": r"\bRAG\b|retrieval[- ]augmented",
    "reasoning": r"\breasoning\b|chain[- ]of[- ]thought",
    "China bloc": r"\bqwen\b|deepseek|kimi|moonshot|\bglm-|minimax",
}

# Channel names group into what a community is for.
KIND = [
    ("help / support", r"help|support|question|troubleshoot|beginner"),
    ("general chat", r"general|off-topic|lounge|random|chat"),
    ("research / papers", r"research|paper|reading|theory|arxiv"),
    ("builds / showcase", r"showcase|share|demo|project|creation|built"),
    ("announcements", r"announce|release|news|changelog"),
]


def half(name: str) -> str:
    return f"20{name[:2]}H{1 if int(name[3:5]) <= 6 else 2}"


def month(name: str) -> str:
    return f"20{name[:5]}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--top", type=int, default=16)
    args = parser.parse_args(argv)

    msgs: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    total_msgs: collections.Counter = collections.Counter()
    seen: dict[str, list[str]] = collections.defaultdict(list)
    kinds: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    words: collections.Counter = collections.Counter()
    hits: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    channel_days = 0
    compiled = {k: re.compile(v, re.I) for k, v in PATTERNS.items()}
    kind_re = [(k, re.compile(v, re.I)) for k, v in KIND]

    for path in sorted(ARTICLES.glob("*.md")):
        body = FRONT.sub("", path.read_text(encoding="utf-8", errors="replace"))
        disc = sections_of(body).get("discord", "")
        if not disc:
            continue
        h, mo = half(path.name), month(path.name)
        words[h] += len(disc.split())
        for name, pattern in compiled.items():
            hits[name][h] += len(pattern.findall(disc))
        for c in CHANNEL.finditer(disc):
            server, chan, n = c.group("server").strip(), c.group("chan"), int(c.group("n"))
            channel_days += 1
            msgs[server][mo] += n
            total_msgs[server] += n
            seen[server].append(mo)
            for label, rx in kind_re:
                if rx.search(chan):
                    kinds[server][label] += n
                    break

    months = sorted({m for v in msgs.values() for m in v})
    periods = [p for p in sorted(words) if words[p] > 20000]

    lines = [
        "# The Discord telemetry",
        "",
        "Generated by `analysis/methods/discord.py`. Message counts are declared in the",
        "channel headings themselves, so this is behavioural data rather than editorial",
        "summary.",
        "",
        f"**{channel_days:,} channel-day records · {sum(total_msgs.values()):,} messages · "
        f"{len(msgs)} servers · {months[0]} → {months[-1]}**",
        "",
        "> Discord sampling stops in March 2026 when the newsletter dropped the section.",
        "> Nothing here speaks to 2026H2, and any apparent decline after that date is the",
        "> instrument, not the field.",
        "",
        "## Community lifecycle",
        "",
        "| Server | Messages | Active | First | Last | Busiest channel type |",
        "|---|---|---|---|---|---|",
    ]
    for server, n in total_msgs.most_common(args.top):
        ms = sorted(seen[server])
        top_kind = kinds[server].most_common(1)
        lines.append(f"| {server[:34]} | {n:,} | {len(set(ms))} mo | {ms[0]} | {ms[-1]} | "
                     f"{top_kind[0][0] if top_kind else '—'} |")
    lines.append("")

    # died vs survived to the end of Discord coverage
    last_month = months[-1]
    died = [(s, n) for s, n in total_msgs.items()
            if max(seen[s]) < "2025-10" and n > 3000]
    lines += ["### Servers that went quiet before coverage ended", "",
              ", ".join(f"{s} ({n:,})" for s, n in sorted(died, key=lambda x: -x[1])[:12]) or "none",
              ""]

    lines += ["## Discord as a third surface", "",
              "The same patterns as `sections.py`, measured inside the Discord recap.",
              "Mentions per 10⁴ words.", "",
              "| Pattern | " + " | ".join(periods) + " |",
              "|---|" + "|".join(["---"] * len(periods)) + "|"]
    for name in PATTERNS:
        lines.append(f"| `{name}` | " + " | ".join(
            f"{hits[name][p]/words[p]*10000:.1f}" for p in periods) + " |")
    lines.append("")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"{channel_days:,} channel-days · {sum(total_msgs.values()):,} messages · {len(msgs)} servers")
    print("\ntop servers:")
    for s, n in total_msgs.most_common(8):
        print(f"  {n:>9,}  {s[:38]:<40} {min(seen[s])} → {max(seen[s])}")
    print("\ncommunity surface, mentions/10k words:")
    print(f"  {'':<14}" + "".join(f"{p:>9}" for p in periods))
    for name in PATTERNS:
        print(f"  {name:<14}" + "".join(f"{hits[name][p]/words[p]*10000:>9.1f}" for p in periods))
    return 0


if __name__ == "__main__":
    sys.exit(main())
