#!/usr/bin/env python3
"""Does the hype gradient survive a change of baseline? Partly.

Every headline ratio in this book is a fold-change from a baseline period to a
recent one, and the baseline was chosen once, early, for a reason that had
nothing to do with the answer: 2024H1 is where the corpus's section headings
first stabilise. That is a defensible choice and not the only defensible one,
which makes it worth asking how much the conclusions depend on it.

Three baselines are compared, all against 2026H1:

  * 2024H1 entire — 47,175 words of Twitter recap, but it spans the format
    changes of March 2024 and includes recaps that read "TO BE COMPLETED".
  * The stable publishing regime from 2024-05-20, which changepoints.py
    identifies as the start of the corpus's long steady period. Cleaner, and
    only 18,139 words.
  * 2024H2 entire — 54,109 words, no format churn, but six months later, so
    part of the rise being measured has already happened.

What holds and what does not:

  * *Directions* mostly hold. fine-tuning and RAG fall, agents and the China
    bloc rise, on every baseline in both surfaces. The one exception is
    reasoning, which rises from 2024H1 and the stable core and falls from
    2024H2 — so even its sign is baseline-dependent.
  * *Gradients* almost all fail. Agents show a 4.5:1 announcement-to-practice
    ratio from 2024H1 and 6.2:1 from the stable core, but 1.0:1 from 2024H2,
    where the gradient disappears. The practice-side baseline is doing the
    work: the 2024H1 Reddit recap is only 30,947 words and its agent density
    (15.3) is three times its 2024H2 value (5.0). The China bloc's
    practitioner lead holds on two baselines and inverts on the third. Only
    RAG's gradient survives all three.

So the method is sound and the instrument is thinner than the conclusions drawn
from it. A gradient measured against one baseline is a lead, not a result.

Usage:
    python3 analysis/methods/sensitivity.py
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
import sys

from recaps import split

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
ARTICLES = REPO / "articles"
OUT = REPO / "analysis" / "sensitivity.md"

PATTERNS = {
    "agentic": r"\bagentic\b|\bagents?\b",
    "China bloc": r"\bqwen\b|deepseek|kimi|moonshot|\bglm-|minimax",
    "reasoning": r"\breasoning\b|chain[- ]of[- ]thought",
    "fine-tuning": r"fine[- ]?tun|\bLoRA\b",
    "RAG": r"\bRAG\b|retrieval[- ]augmented",
}

BASELINES = {
    "2024H1": ("23-12-01", "24-07-01"),
    "stable core (2024-05-20+)": ("24-05-20", "24-07-01"),
    "2024H2": ("24-07-01", "25-01-01"),
}
RECENT = ("26-01-01", "26-07-01")   # 2026H1
SOURCES = ("twitter", "reddit")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.parse_args(argv)

    compiled = {k: re.compile(v, re.I) for k, v in PATTERNS.items()}
    words: collections.Counter = collections.Counter()
    hits: collections.Counter = collections.Counter()
    spans = dict(BASELINES, RECENT=RECENT)

    for path in sorted(ARTICLES.glob("*.md")):
        name = path.name
        tags = [t for t, (lo, hi) in spans.items() if lo <= name < hi]
        if not tags:
            continue
        secs = split(path)
        for source in SOURCES:
            text = secs.get(source, "")
            if not text:
                continue
            n = len(text.split())
            for tag in tags:
                words[(tag, source)] += n
                for k, rx in compiled.items():
                    hits[(tag, source, k)] += len(rx.findall(text))

    def density(tag: str, source: str, k: str) -> float:
        w = words[(tag, source)]
        return hits[(tag, source, k)] / w * 10000 if w else 0.0

    def fold(tag: str, source: str, k: str) -> float:
        base = density(tag, source, k)
        return density("RECENT", source, k) / base if base else float("inf")

    lines = ["# Baseline sensitivity", "",
             "Generated by `analysis/methods/sensitivity.py`. Fold change to 2026H1 from three",
             "different baselines, inside a fixed recap section.", "",
             "| Baseline | Twitter words | Reddit words |", "|---|---|---|"]
    for tag in BASELINES:
        lines.append(f"| {tag} | {words[(tag, 'twitter')]:,} | {words[(tag, 'reddit')]:,} |")
    lines += ["", "Two separate questions. **Direction**: does the pattern rise, or fall, on",
              "every baseline in both surfaces? **Gradient**: does the *same surface* move more,",
              "on every baseline? The first is what a claim like \"fine-tuning declined\" needs.",
              "The second is what the hype gradient needs.", "",
              "| Pattern | " + " | ".join(f"{t} tw / rd" for t in BASELINES)
              + " | direction | gradient |",
              "|---|" + "|".join(["---"] * (len(BASELINES) + 2)) + "|"]

    print(f"{'pattern':<13}" + "".join(f"{t[:20]:>21}" for t in BASELINES)
          + "  direction  gradient")
    for k in PATTERNS:
        cells, ratios, folds = [], [], []
        for tag in BASELINES:
            tw, rd = fold(tag, "twitter", k), fold(tag, "reddit", k)
            cells.append(f"{tw:.1f}× / {rd:.1f}×")
            ratios.append(tw / rd if rd else float("inf"))
            folds += [tw, rd]
        direction = all(f > 1 for f in folds) or all(f < 1 for f in folds)
        # the gradient is stable only if every baseline agrees which surface led
        gradient = all(r > 1.3 for r in ratios) or all(r < 0.77 for r in ratios)
        d, g = ("yes" if direction else "**no**"), ("yes" if gradient else "**no**")
        lines.append(f"| `{k}` | " + " | ".join(cells) + f" | {d} | {g} |")
        print(f"  {k:<11}" + "".join(f"{c:>21}" for c in cells)
              + f"{'  robust' if direction else '  UNSTABLE':>11}"
              + f"{'  robust' if gradient else '  UNSTABLE':>11}")

    lines += ["", "> Directions mostly survive: `fine-tuning` and `RAG` fall, `agentic` and the",
              "> China bloc rise, whichever baseline you pick. **No gradient survives.**",
              "> `agentic` shows a 4.5:1 announcement-to-practice ratio from 2024H1, 6.2:1 from",
              "> the stable core, and 1.0:1 from 2024H2 — where it disappears. The practice-side",
              "> baseline drives it: the 2024H1 Reddit recap is 30,947 words and its agent",
              "> density is three times its 2024H2 value. Treat a single-baseline gradient as a",
              "> lead to investigate, never as a result.", ""]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nwrote {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
