#!/usr/bin/env python3
"""What the newsletter was called, versus what the archive says it was called.

The archive stores a `title` in each issue's front matter, and that field
degrades badly: the share of issues titled some variant of "not much happened
today" climbs from 8% in late 2023 to 85% in 2026. Read at face value, that is
a finding about the field — the news thinned out, and the editor stopped
bothering to name the day.

It is not. It is a finding about the mirror. The subject line the issue was
actually published under is recovered in `analysis/published_subjects.tsv`, and
on the same issues it is templated only a small fraction of the time. Days the
archive files as "not much happened today" went out as "Sam Altman's AI
Combinator", "The Custom ASIC Thesis", "Is Harness Engineering real?".

Two lessons, and the second is the one worth keeping:

1. The stored title is not the published title. Do not measure it as if it were.
2. A series that moves monotonically across the whole window, in the direction
   your argument wants, deserves a check against a second source before it is
   believed. This one did not survive that check.

The comparison can only be made from 2026-01-26 onward, which is as far back as
the recovered mailbox reaches. That is enough: it covers the stretch where the
stored series does almost all of its climbing.

Usage:
    python3 analysis/methods/titles.py
"""

from __future__ import annotations

import argparse
import collections
import csv
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
ARTICLES = REPO / "articles"
SUBJECTS = REPO / "analysis" / "published_subjects.tsv"
OUT = REPO / "analysis" / "titles.md"

FRONT = re.compile(r"\A---\n(.*?)\n---\n", re.S)
TITLE = re.compile(r"^title:\s*(.*)$", re.M)
KEY = re.compile(r"^\w[\w-]*:")
# The template and its close relatives, as they appear in both fields.
TEMPLATED = re.compile(r"not much happened|quiet day", re.I)


def half(name: str) -> str:
    return f"20{name[:2]}H{1 if int(name[3:5]) <= 6 else 2}"


def stored_title(text: str) -> str:
    """The `title` field, following YAML folded scalars (`title: >-`)."""
    m = FRONT.match(text)
    if not m:
        return ""
    mt = TITLE.search(m.group(1))
    if not mt:
        return ""
    value = mt.group(1).strip().strip("\"'")
    if value in (">", ">-", "|", "|-"):
        rest = m.group(1)[mt.end():].split("\n")
        return " ".join(ln.strip() for ln in rest[1:3]
                        if ln.strip() and not KEY.match(ln.strip()))
    return value


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.parse_args(argv)

    titles: dict[str, str] = {}
    stored: dict[str, list[bool]] = collections.defaultdict(list)
    for p in sorted(ARTICLES.glob("*.md")):
        t = stored_title(p.read_text(encoding="utf-8", errors="replace"))
        titles[p.name[:8]] = t
        stored[half(p.name)].append(bool(TEMPLATED.search(t)))

    if not SUBJECTS.exists():
        print(f"missing {SUBJECTS.relative_to(REPO)}; run extract_commentary_gmail.py",
              file=sys.stderr)
        return 1
    with SUBJECTS.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))

    published: dict[str, list[bool]] = collections.defaultdict(list)
    rescued: list[tuple[str, str, str]] = []
    paired = 0
    for r in rows:
        day = r["covers"][2:]
        if day not in titles:
            continue
        paired += 1
        subject = r["subject"].replace("[AINews]", "").strip()
        was = bool(TEMPLATED.search(titles[day]))
        now = bool(TEMPLATED.search(subject))
        published[half(day)].append(now)
        if was and not now:
            rescued.append((day, titles[day], subject))

    lines = ["# Stored titles versus published subject lines", "",
             "Generated by `analysis/methods/titles.py`.", "",
             "## The stored `title` field, whole corpus", "",
             "| Half | Issues | Templated | Share |", "|---|---|---|---|"]
    for h in sorted(stored):
        v = stored[h]
        lines.append(f"| {h} | {len(v)} | {sum(v)} | {100 * sum(v) / len(v):.1f}% |")

    lines += ["", "## The same issues, by what was actually sent", "",
              f"Covers the {paired} issues recovered from the mailbox "
              "(2026-01-26 onward).", "",
              "| Half | Issues | Stored templated | Published templated |",
              "|---|---|---|---|"]
    for h in sorted(published):
        pub, sto = published[h], [x for d, x in
                                  ((d, bool(TEMPLATED.search(titles[d]))) for d in titles)
                                  if half(d) == h]
        lines.append(f"| {h} | {len(pub)} | {100 * sum(sto) / max(len(sto), 1):.1f}% | "
                     f"{100 * sum(pub) / len(pub):.1f}% |")

    lines += ["", f"**{len(rescued)} of {paired} issues the archive files under a "
                  "templated title were published under a real headline.**", "",
              "| Day | Stored title | Published subject |", "|---|---|---|"]
    for day, was, now in rescued[:25]:
        lines.append(f"| 20{day} | {was} | {now} |")
    lines += ["", "> The stored series rises monotonically and the published series does",
              "> not. The rise measures the mirror, not the newsletter, and not the field.",
              ""]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    print("stored `title` templated, by half-year:")
    for h in sorted(stored):
        v = stored[h]
        print(f"  {h}  {sum(v):>3}/{len(v):<4} {100 * sum(v) / len(v):5.1f}%")
    print("published subject templated, same issues:")
    for h in sorted(published):
        v = published[h]
        print(f"  {h}  {sum(v):>3}/{len(v):<4} {100 * sum(v) / len(v):5.1f}%")
    print(f"{len(rescued)} of {paired} stored-templated issues had a real published headline")
    return 0


if __name__ == "__main__":
    sys.exit(main())
