#!/usr/bin/env python3
"""Group the archive's 2,241 raw topic tags into domains and track them over time.

The tag vocabulary is heavily fragmented — `fine-tuning`, `finetuning` and
`model-fine-tuning` are the same thing, and the top 200 tags cover only 64% of
all tag instances. So domains are matched by regex against the tag text rather
than by an exact lookup, which pulls in the long tail too.

A tag may land in more than one domain (`agentic-coding` is both agents and
coding); shares are therefore per-domain and do not sum to 100%.
"""

from __future__ import annotations

import collections
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
INDEX = REPO / "analysis" / "index.json"
OUT = REPO / "analysis" / "domains.md"

DOMAINS: dict[str, str] = {
    "Agents & tool use": r"agent|tool-use|function-call|computer-use|orchestrat|workflow|mcp\b|browser-use",
    "Coding": r"coding|code-gen|code-exec|software-eng|software-dev|cli-tool|programming|swe\b|debugg",
    "Reasoning & RL": r"reason|chain-of-thought|reinforcement|rlhf|rlaif|\bdpo\b|reward|post-training|math|\bcot\b|test-time",
    "Vision & image": r"vision|multimodal|multimodality|\bocr\b|image|diffusion|text-to-image|visual",
    "Video": r"video|text-to-video|world-model",
    "Audio & speech": r"audio|speech|voice|\btts\b|text-to-speech|music|asr\b|transcri",
    "Robotics & embodied": r"robot|humanoid|embodied|autonomous-driv|drone|physical-ai",
    "Training & data": r"train|pretrain|fine-?tun|synthetic-data|dataset|distill|model-merg|scaling-law|lora|curriculum|data-quality",
    "Efficiency & hardware": r"quantiz|inference|latency|speculative|kv-cache|\bgpu\b|cuda|hardware|fp8|fp4|throughput|serving|on-device|local-inference|compress|optimiz|efficien|tpu|chip",
    "Context & memory": r"long-context|context-window|context-length|memory|prompt-cach|context-engineer|persistent",
    "Retrieval & search": r"\brag\b|retrieval|embedding|semantic-search|vector|search|knowledge-base",
    "Safety & security": r"safety|alignment|security|cyber|prompt-inject|jailbreak|privacy|sandbox|interpretab|hallucinat|red-team|misuse|guardrail",
    "Policy & business": r"regulat|policy|funding|pricing|enterprise|partnership|licens|ethic|geopolit|export|lawsuit|copyright|acquisition|ipo\b|market",
    "Evaluation": r"benchmark|\beval|leaderboard|arena|model-comparison|model-performance",
    "Architecture": r"\bmoe\b|mixture-of-experts|attention|transformer|architecture|tokeniz|state-space|mamba|sparse|multi-token",
    "Open source": r"open-source|open-weight|open-model|permissive|apache",
}
COMPILED = {name: re.compile(pattern) for name, pattern in DOMAINS.items()}


def half(date: str) -> str:
    return f"{date[:4]}H{1 if int(date[5:7]) <= 6 else 2}"


def domains_of(record: dict) -> set[str]:
    """Which domains this issue touches, via its topic tags."""
    hits = set()
    for tag in record.get("topics", []):
        tag = tag.strip().lower()
        for name, pattern in COMPILED.items():
            if pattern.search(tag):
                hits.add(name)
    return hits


def table(rows: list[tuple], headers: tuple) -> list[str]:
    lines = ["| " + " | ".join(map(str, headers)) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines += ["| " + " | ".join(map(str, row)) + " |" for row in rows]
    return lines + [""]


def main() -> int:
    records = json.loads(INDEX.read_text(encoding="utf-8"))
    periods = sorted({half(r["date"]) for r in records})
    buckets = {p: [r for r in records if half(r["date"]) == p] for p in periods}

    # Precompute once; the regex sweep is the expensive part.
    tagged = [(r, domains_of(r)) for r in records]
    by_period = {p: [d for r, d in tagged if half(r["date"]) == p] for p in periods}

    share = {
        name: {p: sum(1 for d in by_period[p] if name in d) / len(by_period[p]) * 100 for p in periods}
        for name in DOMAINS
    }

    lines = [
        "# Domain evolution",
        "",
        "Generated by `analysis/domains.py`. Share of each period's issues touching a",
        "domain. Domains overlap by design, so columns do not sum to 100%.",
        "",
    ]
    lines += table([("*(issues)*",) + tuple(f"*{len(buckets[p])}*" for p in periods)], ("Domain",) + tuple(periods))

    order = sorted(DOMAINS, key=lambda n: -sum(share[n].values()))
    rows = [tuple([name] + [f"{share[name][p]:.0f}%" for p in periods]) for name in order]
    lines += table(rows, ("Domain",) + tuple(periods))

    # Biggest structural shifts, first full year vs most recent 12 months.
    early = [d for r, d in tagged if r["date"][:4] == "2024"]
    late = [d for r, d in tagged if r["date"] >= "2025-08-01"]
    deltas = []
    for name in DOMAINS:
        a = sum(1 for d in early if name in d) / len(early) * 100
        b = sum(1 for d in late if name in d) / len(late) * 100
        deltas.append((b - a, name, a, b))
    deltas.sort(reverse=True)
    lines += ["## Shift: 2024 vs. last 12 months", ""]
    lines += table(
        [(name, f"{a:.0f}%", f"{b:.0f}%", f"{d:+.0f}pp") for d, name, a, b in deltas],
        ("Domain", "2024", "Last 12mo", "Change"),
    )

    # What the long tail looks like inside each domain, for auditing the regexes.
    lines += ["## Domain composition", "", "Top raw tags matched into each domain, for auditing.", ""]
    for name in order:
        counter: collections.Counter = collections.Counter()
        for record in records:
            for tag in {t.strip().lower() for t in record.get("topics", [])}:
                if COMPILED[name].search(tag):
                    counter[tag] += 1
        top = ", ".join(f"`{t}`" for t, _ in counter.most_common(10))
        lines += [f"- **{name}** ({len(counter)} distinct tags): {top}"]
    lines += [""]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO)}")
    for d, name, a, b in deltas[:5]:
        print(f"  {name:<24} {a:5.0f}% -> {b:5.0f}%  ({d:+.0f}pp)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
